name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  'Adrian' # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: ${{ steps.hello.outputs.time }} # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'